import Link from 'next/link';
import './globals.css'
export const metadata = {
  title: 'Invoice Manager',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
      <div className='grid grid-cols-1 gap-4'>
        <header className='flex justify-center ...'>
          
          <nav className='p-2 text-purple-600 ... no-underline hover:underline ...'> 
            <Link className='pl-3'   href="/">Home</Link>            
            <Link className='pl-3' href="/invoices">View-Invoices</Link>
            <Link className='pl-3' href="/invoices/create-invoice">Create-Invoice</Link>
          </nav>
        </header>
        <main>{children}</main>
      </div>
      </body>
    </html>
  )
}
