import Link from 'next/link';
import './globals.css'
export const metadata = {
  title: 'Invoice Manager',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
      <div className='justify-center'>
        <header className='justify-center'>
          
          <nav className='justify-center'> 
            <Link className='gap-y-px'   href="/">Home</Link>            
            <Link href="/invoices">View Invoices</Link>
            <Link href="/invoices/create-invoice">Create Invoice</Link>
          </nav>
        </header>
        <main>{children}</main>
      </div>
      </body>
    </html>
  )
}
