import { Metadata } from "next";
import { ReactNode } from 'react';

export const metadata: Metadata = {
  title: "Invoice-manger",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <html>
      <body>
        <div>
          <header>
            <nav>
              <a href="/">Home</a>
              <a href="/invoices">Invoices</a>
              <a href="/create-invoice">Create Invoice</a>
            </nav>
          </header>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
